appointer/activity/urls.py
from django.urls import path, re_path
from appointer.activity import views

app_name = 'core'
urlpatterns = [
    path('',views.activities_list,name='activities_list'),
    path('new', views.new_activity, name='new_activity'),
    re_path(r'(?P<pk>\d+)$', views.activity_details, name='activity_details'),
    re_path(r'(?P<pk>\d+)/delete$', views.delete_activity, name='delete_activity'),
    re_path(r'(?P<pk>\d+)/appoint$', views.appoint, name='new_appoint'),
    re_path(r'(?P<pk>\d+)/appoint/close$', views.close_appoint, name='close_appoint'),
    re_path(r'(?P<pk>\d+)/appoint/(?P<app_pk>\d+)/edit$', views.appoint_edit, name='edit_appoint'),
    re_path(r'(?P<pk>\d+)/break$', views.take_break, name='take_break'),
    re_path(r'(?P<pk>\d+)/break/resume$', views.resume_break, name='resume_break'),
    re_path(r'(?P<pk>\d+)/appoints/view$', views.list_appoints, name='view_appoints'),
]

appointer/core/urls.py
from django.urls import path
from appointer.core import views
from django.contrib.auth import views as auth_views

app_name = 'core'
urlpatterns = [
    path('',views.home,name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='core:home'), name='logout'),
    path('about/', views.about, name='about'),
    path('password_reset/', views.reset_password, name='reset_password'),
    path('password_reset/<str:hash>', views.reset_password_confirm, name='reset_password_confirm')
]

appointer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('appointer.core.urls',namespace='core')),
    path('activities/', include('appointer.activity.urls', namespace='activity')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appointer/core/models.py
import re
from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager

class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField('username', max_length=30, unique=True, validators=[validators.RegexValidator(regex=re.compile('^[\w.@+-]+$'), message='Invalid username', code='invalid')])
    email = models.EmailField('email', unique=True)
    name = models.CharField('name', max_length=100, blank=True)
    is_active = models.BooleanField('active', blank=True, default=True)
    is_staff = models.BooleanField('staff', blank=True, default=False)
    date_joined = models.DateTimeField('join date', auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return str(self)

    def get_open_activities(self):
        count = 0
        for act in self.activities.all():
            if act.get_open_appointments().count() > 0:
                count = count + 1

        return count 

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

class Socials(models.Model):
    url = models.CharField('url', max_length=200, blank=False, null=False)
    icon = models.CharField('icon', max_length=50, blank=False, null=True)
    alt_text = models.CharField('alt_text', max_length=200, blank=False, null=False)
    is_main_site = models.BooleanField('is_main_site', null=False, default=False)

    def __str__(self):
        return self.alt_text

    class Meta:
        verbose_name = 'Social'
        verbose_name_plural = 'Socials'

class PasswordReset(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='password_resets')
    token = models.CharField('token', null=False, blank=False, max_length=255)
    created_at = models.DateTimeField('created_at', null=False, blank=False, auto_now_add=True)
    expired = models.BooleanField('expired', default=False, null=False, blank=False)
    confirmed = models.BooleanField('confirmed', default=False, blank=True)

    def __str__(self):
        return '{0} em {1}'.format(self.user, self.created_at)

    class  Meta:
        verbose_name = 'Reset de senha'
        verbose_name_plural = 'Resets de senha'
        ordering = ['-created_at']

appointer/core/forms.py
from django import forms
from .models import PasswordReset
from .utils import password_reset_hash, send_mail
from django.contrib.auth import get_user_model

Usuario = get_user_model()

class PasswordResetForm(forms.Form):
    email = forms.EmailField(label='Email')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if Usuario.objects.filter(email=email).exists():
            return email
        else:
            raise forms.ValidationError('Nenhum usuario encontrado com o email {0}'.format(email))

    def save(self):
        user = Usuario.objects.get(email=self.cleaned_data.get('email'))
        res = PasswordReset(user=user, token=password_reset_hash(user.email))
        res.save()
        send_mail('BastielCos - Redefina sua senha','reset_password_mail.html', {'hash':res.token}, [user.email])

class PasswordResetConfirmForm(forms.Form):
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmação de senha', widget=forms.PasswordInput)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Senhas divergentes")
        return password2

    def save(self, user=None, commit=True):
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

appointer/core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.utils import timezone as tz
import calendar
from .forms import PasswordResetForm, PasswordResetConfirmForm
from .models import PasswordReset
import datetime
from django.contrib import messages

def home(req):
    count = 0
    act = []
    if req.user.is_authenticated:
        for activity in req.user.activities.all():
            weeks = []
            for week in calendar.monthcalendar(tz.now().year, tz.now().month):
                count = count + 1
                days = []
                for day in week:
                    if day == 0:
                        used = False
                        timespent = 0
                    else:
                        used = True
                        timespent = activity.total_appointed_time_day(day, tz.now().month, tz.now().year)
                    days.append({"day":day, "used":used, "timespentint":timespent})
                weeks.append(days)
            act.append({'name':activity.name, 'color':activity.color, 'appoints':weeks})
    return render(req, 'home.html', {'chartData':{"activities":act}})

def about(req):
    return render(req, 'about.html')

def reset_password(request):
    form = PasswordResetForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request, 'Requisição enviada! Verifique seu email')
        return redirect('core:home')
        
    return render(request, 'password_reset.html', {'form':form})

def reset_password_confirm(request, hash):
    reset = PasswordReset.objects.filter(token=hash).first() # pylint: disable=no-member
    if reset == None:
        messages.error(request, 'Requisição não encontrada!')
        return redirect('core:home')

    if not reset.expired:
        if (((datetime.datetime.now() - reset.created_at).total_seconds())/60) > 30:
            reset.expired = True
            reset.save()
            messages.error(request, 'Requisição expirada! Tente novamente')
            return redirect('core:home')
        
        form = PasswordResetConfirmForm(request.POST or None)
        if form.is_valid():
            reset.confirmed = True
            reset.save()
            form.save(user=reset.user)
            messages.success(request, 'Senha alterada com sucesso!')
            return redirect('core:login')

        return render(request, 'password_reset_confirm.html', {'form':form})

    return redirect('core:home')

appointer/core/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <div class="col-6 mx-auto mt-3">
        <div class="card-deck">
            <div class="card bg-transparent text-white">
                <img src="{% static 'img/about-img.png' %}" class="card-img-top" alt="Images">
                <div class="card-body">
                    <h5 class="card-title">Images</h5>
                    <p class="card-text">Images created w/ Freepik Stories</p>
                    <a class='btn btn-light stretched-link' target="_blank" href="https://stories.freepik.com/">See it here</a>
                </div>
            </div>
            <!--  -->
            <div class="card bg-transparent text-white">
                <img src="{% static 'img/about-chart.png' %}" class="card-img-top" alt="Charts">
                <div class="card-body">
                    <h5 class="card-title">Charts</h5>
                    <p class="card-text">Charts created w/ Chartjs</p>
                    <a class='btn btn-light stretched-link' target="_blank" href="https://www.chartjs.org/">See it here</a>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}
    

appointer/core/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load menu %}
<html lang="en" class="h-100">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>DeepLab - Appointer</title>
    <link rel="shortcut icon" href="{% static 'img/favicon-white.ico' %}">
    <link rel="stylesheet" href="{% static 'css/custom.min.css' %}">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/146fe99a3a.js" crossorigin="anonymous"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('.toast').toast('show');
        });
    </script>
    {% block pagescript %}{% endblock %}
</head>
<body class="dl-body d-flex flex-column h-100">
    <main role="main" class='flex-shrink-0 mb-3'>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a href="/" class="navbar-brand">
                <img src="{% static 'img/favicon-white.png' %}" alt="DeepLab">    
                Appointer
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                {% create_menu request.path user.is_authenticated %}
            </div>
        </nav>
        <!-- Messages block -->
        {% if messages %}
            <div aria-live="polite" aria-atomic="true" style="position: relative; z-index: 10000;">
                <div class="mt-3 mr-3" style="position: absolute; top: 0; right: 0;">
                    {% for m in messages %}
                        <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-autohide="false">
                            <div class="toast-header bg-{{ m.tags }}">
                                <strong class="mr-auto">{{ m.tags|title }}</strong>
                                <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="toast-body">
                                <p class="m-0">{{ m }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        {% block body %}{% endblock %}
    </main>
    <footer class="bg-dark mt-auto py-3">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center">
                    {% for social in social_media_links %}
                        <a href="{{ social.url }}" class="text-white {% if not forloop.last %} mr-3 {% endif %}"><i class="{{ social.icon }}"></i></a>
                    {% endfor %}
                </div>
                <div class="col-12 text-center text-white">
                    <p>
                        Developed by 
                        <a href="{{ main_site.url }}" target="_blank" class="text-white">{{ main_site.alt_text }}</a>
                    </p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

appointer/core/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block pagescript %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            var ctx = $("#progressChart");
            if(ctx !== undefined){
                var raw = JSON.parse(ctx.data('content').replace(/'/g, "\"").replace(/False/g, "0").replace(/True/g, "1"));
                var dataset = [];
                var chartData = [];
                var chartLabels = [];
                raw.activities.forEach(activity => {
                    chartLabels = [];
                    chartData = [];
                    activity.appoints.forEach(week=>{
                        week.forEach(day =>{
                            if(day.used === 1){
                                chartLabels.push(day.day);
                                chartData.push(parseInt(day.timespentint));
                            }
                        });
                    });
                    dataset.push({
                        label: activity.name,
                        data: chartData,
                        fill: false,
                        borderColor: activity.color
                    });
                });

                Chart.defaults.global.defaultFontColor = 'white';
                var myChart = new Chart(ctx, {
                    type: 'line',
                    data: {
                        labels: chartLabels,
                        datasets: dataset
                    },
                    options: {
                        scales: {
                            yAxes: [{
                                ticks: {
                                    beginAtZero: true
                                }
                            }]
                        }
                    }
                });
            }
        });
    </script>
{% endblock %}
{% block body %}
    <div class="container mt-3">
    {% if user.is_authenticated %}
        <div class="d-flex flex-column flex-lg-row justify-content-center text-white">
            {% if user.get_open_activities > 0 %}
                <div>
                    <h6 class="display-4">Activities in progress</h6>
                    <div class="btn-group-vertical mt-2" role='group' aria-label="activities">
                        {% for act in user.activities.all %}
                            {% if act.get_open_appointments.count > 0 %}
                                <a href="{% url 'activity:activity_details' act.id %}" class="btn btn-primary">
                                    <i class="fas fa-share"></i>
                                    {{ act.name }}
                                </a>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
            <div>
                <h3 class='display-4'>Activities progress (in seconds)</h3>
                <canvas id="progressChart" data-content="{{ chartData }}"></canvas>
            </div>
        </div>
    {% else %}
        <div class="text-white d-flex flex-md-row flex-column-reverse justify-content-md-between">
            <div class="align-self-md-center">
                <h6 class="display-4">Time Management</h6>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam inventore iusto, voluptate odit est odio. In ab officia, dicta architecto rem dolore doloribus eum? Saepe sequi nemo odit dolore fugit.</p>
            </div>
            <div>
                <img class="img-fluid" src="{% static 'img/tm.png' %}" alt="Time management">
            </div>
        </div>
    {% endif %}
    </div>
{% endblock %}

appointer/core/templates/login.html
{% extends "base.html" %}
{% block body %}
{% load widget_tweaks %}
    <div class="text-center mx-auto align-items-center">
        <i class="fas fa-users fa-5x text-white mt-3 bg-primary rounded-circle p-4"></i>
        <form method="POST" class="text-white p-4">    
            {% csrf_token %}
            {% if form.non_field_errors %}
                <div class="d-flex flex-row justify-content-center mb-3 text-center col-md-6 col-10 mx-auto">
                    <div class="d-flex text-white bg-danger p-3 align-items-center" style="border-radius: 25px 0px 0px 25px">
                        <span class="fas fa-skull-crossbones fa-2x text-white"></span>
                    </div>
                    <div class="d-flex align-items-center alert-danger" style="border-radius: 0px 25px 25px 0px">
                        {% for e in form.non_field_errors %}
                            <p class="m-0 p-3">{{ e }}</p>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
            {% for f in form %}
                <div class="form-row form-group d-flex align-items-center text-center">
                    <div class="col-md-6 col-10 mx-auto input-group">
                        <span class="input-group-prepend">
                            <div class="input-group-text bg-white pl-4 pr-3" style="border-radius: 25px 0px 0px 25px">
                                {% if f.label == 'Username' %}
                                    <i class="fas fa-user"></i>
                                {% else %}
                                    <i class="fas fa-lock"></i>
                                {% endif %}
                            </div>
                        </span>
                        {% render_field f class="form-control form-control-lg" placeholder=f.label style="border-radius: 0px 25px 25px 0px"%}
                    </div>
                </div>
                {{ f.errors }}
            {% endfor %}
            <div class="col-md-6 col-10 mx-auto text-right">
                <a href="{% url 'core:reset_password' %}" class="text-decoration-none text-primary">Forgot password?</a>
            </div>
            <br>
            <button type='submit' class="btn btn-lg btn-primary px-5 rounded-pill">Login</button>
        </form>
        <p class="text-white">Or</p>
        <a href="#" class="btn btn-lg btn-primary">
            <i class="fab fa-facebook-f mr-3"></i>
            Continue with Facebook
        </a>
    </div>
{% endblock %}

appointer/core/templates/menu.html
<ul class="navbar-nav">
    {% for menu in menus %}
        {% if menu.link == absolutepath %}
            <li class="nav-item active">
                <a href="{{ menu.link }}" class="nav-link">
                    {{ menu.title }} <span class="sr-only">(current)</span>
                </a>
            </li>
        {% else %}
            <li class="nav-item">
                <a href="{{ menu.link }}" class="nav-link">{{ menu.title }}</a>
            </li>
        {% endif %}
    {% endfor %}
</ul>

appointer/core/templates/modal-confirm.html
{% load widget_tweaks %}
<!-- modal confirm -->
<div class="modal fade" id="modalConfirm" tabindex="-1" role="dialog" aria-labelledby="modalConfirmLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalConfirmLabel">{{ title }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
                <div class="modal-body">
                    {{ message }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                    {% if ajax %}
                        <button type="submit" class="btn btn-success" name='btnYesConfirm'>Yes</button>
                    {% else %}
                        <a href="#" class="btn btn-success" name='btnYesConfirm'>Yes</a>
                    {% endif %}
                </div>
        </div>
    </div>
</div>

appointer/core/templates/modal-form.html
{% load widget_tweaks %}
<!-- modal form -->
<div class="modal fade" id="modalForm" tabindex="-1" role="dialog" aria-labelledby="modalFormLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalFormLabel">{{ title }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method='{{ method }}' action='#' id='{{ id }}'>
                {% csrf_token %}
                <div class="modal-body">
                    {% for f in form %}
                        <div class="row">
                            <div class="col-2">{{ f.label_tag }}</div>
                            <div class="col-10">{{ f|add_class:'form-control' }}</div>
                        </div>                                
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

appointer/core/templates/pagination.html
{% if page_obj.paginator.num_pages != 1 %}    
    <nav aria-label="Pagination" class="pagination-outer mt-3">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                <a href="?page=1" class="page-link" aria-label="First">&laquo;</a>
            </li>
            {% for pn in page_obj.paginator.page_range %}
                <li class="page-item {% if pn == page_obj.number %}active{% endif %}">
                    <a href="?page={{ pn }}" class="page-link" {% if pn == page_obj.number %}aria-current="page"{% endif %}>
                        <p>{{ pn }}</p>
                        {% if pn == page_obj.number %}
                            <span class="sr-only">(current)</span>
                        {% endif %}
                    </a>
                </li>
            {% endfor %}
            <li class="page-item">
                <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link" aria-label="Last">&raquo;</a>
            </li>
        </ul>
    </nav>
{% endif %}

appointer/core/templates/password_reset.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block body %}
    <div class="text-center mx-auto align-items-center">
        <h3 class="text-white m-0 mt-3">Informe o email para envio da requisição</h3>
        <form method='POST' class="p-4 pt-0">
            {% csrf_token %}
            {% for f in form %}
                <div class="form-row form-group d-flex align-items-center text-center col-md-6 col-10 mx-auto">
                    {% render_field f class="form-control form-control-lg" placeholder=f.label %}
                </div>
                {{ f.errors }}
            {% endfor %}
            <button type="submit" class="btn btn-light btn-lg px-5 rounded-pill">Continuar</button>
        </form>
    </div>
{% endblock body %}
    

appointer/core/templates/password_reset_confirm.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block body %}
    <div class="text-center mx-auto align-items-center">
        <h3 class="text-white m-0 mt-3">Informe a nova senha</h3>
        <form method='POST' class="p-4 pt-0">
            {% csrf_token %}
            {% for f in form %}
                <div class="form-row form-group d-flex align-items-center text-center col-md-6 col-10 mx-auto">
                    {% render_field f class="form-control form-control-lg" placeholder=f.label %}
                </div>
                {{ f.errors }}
            {% endfor %}
            <button type="submit" class="btn btn-light btn-lg px-5 rounded-pill">Continuar</button>
        </form>
    </div>
{% endblock body %}
    

appointer/core/templates/reset_password_mail.html
<p>
    Redefina sua senha <a href="{{ site }}{% url 'core:reset_password_confirm' hash %}" target="_blank">aqui</a>
</p>