appointer/activity/urls.py
from django.urls import path, re_path
from appointer.activity import views

app_name = 'core'
urlpatterns = [
    path('',views.activities_list,name='activities_list'),
    path('new', views.new_activity, name='new_activity'),
    re_path(r'(?P<pk>\d+)$', views.activity_details, name='activity_details'),
    re_path(r'(?P<pk>\d+)/delete$', views.delete_activity, name='delete_activity'),
    re_path(r'(?P<pk>\d+)/appoint$', views.appoint, name='new_appoint'),
    re_path(r'(?P<pk>\d+)/appoint/close$', views.close_appoint, name='close_appoint'),
    re_path(r'(?P<pk>\d+)/appoint/(?P<app_pk>\d+)/edit$', views.appoint_edit, name='edit_appoint'),
    re_path(r'(?P<pk>\d+)/break$', views.take_break, name='take_break'),
    re_path(r'(?P<pk>\d+)/break/resume$', views.resume_break, name='resume_break'),
    re_path(r'(?P<pk>\d+)/appoints/view$', views.list_appoints, name='view_appoints'),
]

appointer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('appointer.core.urls',namespace='core')),
    path('activities/', include('appointer.activity.urls', namespace='activity')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appointer/activity/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone as tz

class Activity(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='user', related_name='activities', on_delete=models.CASCADE)
    name = models.CharField('name', max_length=30, null=False, blank=False)
    color = models.CharField('color', max_length=7, null=False, blank=False)
    createdat = models.DateTimeField('created at', auto_now_add=True)

    def __str__(self):
        return self.name

    def get_open_appointments(self):
        return self.appointments.filter(timeend__isnull=True)

    def appointments_today(self):
        return self.appointments.filter(starttime__date=tz.now().date())

    def total_appointed_time_day(self, day, month, year):
        totalTime = 0

        for ap in self.appointments.filter(starttime__date=tz.datetime(year,month,day).date()):
            totalTime = totalTime + ap.totaltime()

        return totalTime

    def total_appointed_time(self):
        return str(tz.timedelta(seconds=self.total_appointed_time_day(tz.now().day, tz.now().month, tz.now().year))).split('.', 2)[0]

    def appointments_month(self, month, year):
        return self.appointments.filter(starttime__year=year, starttime__month=month)

    class Meta:
        verbose_name = 'Activity'
        verbose_name_plural = 'Activities'

class Appoint(models.Model):
    activity = models.ForeignKey(Activity, verbose_name='activity', related_name='appointments', on_delete=models.CASCADE)
    starttime = models.DateTimeField('start time', default=tz.now, null=False)
    timeend = models.DateTimeField('end time', null=True)
    
    def has_open_break(self):
        return self.breaks.filter(timeend__isnull=True).count() >= 1

    def totaltime(self):
        if not self.timeend is None:
            diff = (self.timeend - self.starttime).total_seconds()
        else:
            diff = (tz.now() - self.starttime).total_seconds()
        
        breaktime = 0 
        for b in self.breaks.all():
            if b.timeend is None:
                breaktime = breaktime + (tz.now() - b.starttime).total_seconds()
            else:
                breaktime = breaktime + (b.timeend - b.starttime).total_seconds()

        return (diff - breaktime)

    class Meta:
        verbose_name = 'Appointment'
        verbose_name_plural = 'Appointments'

class Break(models.Model):
    appoint = models.ForeignKey(Appoint, verbose_name='appointment', related_name='breaks', on_delete=models.CASCADE)
    starttime = models.DateTimeField('start time', auto_now_add=True)
    timeend = models.DateTimeField('end time', null=True)

    class Meta:
        verbose_name = 'Break'
        verbose_name_plural = 'Breaks'

appointer/activity/forms.py
from django import forms
from django.forms.widgets import TextInput, DateTimeInput
from .models import Activity, Appoint

class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ['name','color']
        widgets = {
            'color': TextInput(attrs={'type': 'color'}),
        }

class AppointForm(forms.ModelForm):
    class Meta:
        model = Appoint
        fields = ['starttime', 'timeend']
        widgets = {
            # attrs={'type':"datetime-local"}
            'starttime': DateTimeInput(),
            'timeend': DateTimeInput()
        }

    timeend = forms.DateTimeField(required=False)

appointer/activity/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.views.generic import TemplateView, ListView, DetailView, View
from django.urls import reverse
from django.utils import timezone as tz
from django.core.paginator import Paginator
from .models import Activity, Appoint, Break
from .forms import ActivityForm, AppointForm
import json
import calendar

@login_required
def activities_list(req):
    paginator = Paginator(req.user.activities.all(), 10)
    page_obj = paginator.get_page(req.GET.get('page') or 1)
    return render(req, 'activities_index.html', {'form':ActivityForm(), 'page_obj':page_obj})

@login_required
def new_activity(req):
    form = ActivityForm(req.POST or None)
    if form.is_valid:
        act = form.save(commit=False)
        act.user = req.user
        act.save()
    if req.is_ajax():
        data = {
            'method':'NEW',
            'success': True, 
            'message': "New activity saved!", 
            'activity':{
                'num':req.user.activities.count(),
                'name':act.name,
                'id': str(act.id)
            }
        }
        return HttpResponse(json.dumps(data), content_type='appication/json')
    else:
        messages.success(req,"New activity saved!")
        return redirect('activity:activities_list')

@login_required
def delete_activity(req, pk):
    instnce = get_object_or_404(Activity, pk=pk)
    instnce.delete()
    if req.is_ajax():
        return HttpResponse(json.dumps({'success':True, 'count':req.user.activities.count()}), content_type="application/json")
    else:
        messages.success(req, "Activity {0} deleted!".format(instnce.name))
        return redirect('activity:activities_list')

@login_required
def appoint(request, pk):
    instance = get_object_or_404(Activity, pk=pk)
    if instance.get_open_appointments().count() > 0:
        if request.is_ajax():
            return HttpResponse(json.dumps({'msg':'open appointment for activity','success':False}), content_type='application/json')
        else:
            return redirect('activity:activity_details', pk=pk)
    app = Appoint(activity=instance)
    app.save()
    if request.is_ajax():
        data = {
            'total' : instance.appointments.count(),
            'success' : True,
            'endUrl': reverse('activity:close_appoint', args=[instance.pk]),
            'breakUrl': reverse('activity:take_break', args=[instance.pk]),
            'appstart': 'now'
        }
        return HttpResponse(json.dumps(data), content_type='application/json')
    else:
        return redirect('activity:activity_details', pk=pk)

@login_required
def close_appoint(request, pk):
    instance = get_object_or_404(Activity, pk=pk)
    if instance.get_open_appointments().count() < 1:
        if request.is_ajax():
            return HttpResponse(json.dumps({'msg':'no open appointment for activity','success':False}), content_type='application/json')
        else:
            return redirect('activity:activity_details', pk=pk)
    app = instance.get_open_appointments().first()
    app.timeend = tz.now()
    app.save()
    if app.has_open_break():
        b = app.breaks.filter(timeend__isnull=True).first()
        b.timeend = app.timeend
        b.save()
        
    if request.is_ajax():
        data = {
            'success':True
        }
        return HttpResponse(json.dumps(data), content_type='application/json')
    else:
        return redirect('activity:activity_details', pk=pk)

@method_decorator(login_required, name='dispatch')
class ActivityDetails(DetailView):
    model = Activity
    template_name = 'activity_details.html'
    context_object_name = 'activity'

    def get(self, request, *args, **kwargs):
        response = super(ActivityDetails, self).get(request, *args, **kwargs)
        return response

    def get_context_data(self, **kwargs):
        ctx = super(ActivityDetails, self).get_context_data(**kwargs)
        instance = get_object_or_404(Activity, id=self.kwargs['pk'])
        count = 0
        weeks = []
        for week in calendar.monthcalendar(tz.now().year, tz.now().month):
            count = count + 1
            days = []
            for day in week:
                if day == 0:
                    used = False
                    total = 0
                    timespent = 0
                    breaks = 0
                else:
                    used = True
                    total = instance.appointments.filter(starttime__date=tz.datetime(tz.now().year, tz.now().month, day).date()).count()
                    timespent = instance.total_appointed_time_day(day, tz.now().month, tz.now().year)
                    breaks = 0
                    for i in instance.appointments.filter(starttime__date=tz.datetime(tz.now().year, tz.now().month, day).date()):
                        breaks = breaks + i.breaks.all().count()
                days.append({"day":day, "used":used, "totalappointments":total, "timespent":str(tz.timedelta(seconds=timespent)).split('.', 2)[0], "breaks":breaks, "timespentint":timespent})
            weeks.append(days)
        ctx['monthlyApp'] = {"weeks":weeks,'color':instance.color}
        return ctx

    def post(self, request, *args, **kwargs):
        i = get_object_or_404(Activity, id=kwargs['pk'])
        form = ActivityForm(request.POST or None, instance=i)
        if form.is_valid:
            act = form.save()
        if request.is_ajax():
            return HttpResponse(json.dumps({'method':'SAVE', 'activity':{'name':act.name, 'id':act.id}}), content_type='appication/json')
        else:
            messages.success(request, "Activity {0} saved!".format(i.name))
            return redirect('activity:activities_list')

activity_details = ActivityDetails.as_view()

@login_required
def take_break(request, pk):
    instance = get_object_or_404(Activity, pk=pk)
    app = instance.get_open_appointments().first()
    if app.has_open_break():
        if request.is_ajax():
            return HttpResponse(json.dumps({'success':False, 'msg':'Activity has open break'}), content_type='application/json')
        else:
            return redirect('activity:activity_details', pk=pk)
    else:
        b = Break(appoint=app)
        b.save()

        if request.is_ajax():
            data = {
                'total' : app.breaks.count(),
                'success' : True,
                'breakstart': 'now',
                'resumeUrl': reverse('activity:resume_break', args=[pk])
            }
            return HttpResponse(json.dumps(data), content_type='application/json')
        else:
            return redirect('activity:activity_details', pk=pk)

@login_required
def resume_break(request, pk):
    instance = get_object_or_404(Activity, pk=pk)
    app = instance.get_open_appointments().first()
    if not app.has_open_break():
        if request.is_ajax():
            return HttpResponse(json.dumps({'success':False, 'msg':'no open breaks to resume'}), content_type='application/json')
        else:
            return redirect('activity:activity_details', pk=pk)

    b = app.breaks.filter(timeend__isnull=True).first()
    b.timeend = tz.now()
    b.save()
    if request.is_ajax():
        data = {
            'total' : app.breaks.count(),
            'success' : True,
            'takeUrl': reverse('activity:take_break', args=[pk])
        }
        return HttpResponse(json.dumps(data), content_type='application/json')
    else:
        return redirect('activity:activity_details', pk=pk)

@login_required
def list_appoints(request, pk):
    instance = get_object_or_404(Activity, pk=pk)
    paginator = Paginator(instance.appointments_month(tz.now().month, tz.now().year).all(), 10)
    page_obj = paginator.get_page(request.GET.get('page') or 1)
    return render(request, 'appoints_list.html', {'act':instance, 'page_obj':page_obj, 'form':AppointForm()})

@login_required
def appoint_edit(request, pk, app_pk):
    instance = get_object_or_404(Appoint, pk=app_pk)
    form = AppointForm(request.POST or None, instance=instance)
    if form.is_valid:
        act = form.save()
        s = True
    else:
        s = False
    if request.is_ajax():
        data = {'success':s}
        return HttpResponse(json.dumps(data), content_type='application/json')
    else:
        messages.success(request, "Appointment edited!")
        return redirect('activity:view_appoints', pk=pk)

appointer/activity/templates/activities_index.html
{% extends "base.html" %}
{% block pagescript %}
<script type="text/javascript">
    $(document).ready(function(){
        var form = $('#actForm');
        var modal = $('#modalForm');
        var modal_confirm = $('#modalConfirm');

        modal.on('hidden.bs.modal', function(e){
            form.trigger('reset');
        });

        modal.on('show.bs.modal', function(e){
            if(!$(e.relatedTarget).data('actid')){
                form.attr('action', '/activities/new');
                $('#modalFormLabel').text('New '+$('#modalFormLabel').text());
            } else {
                $('#modalFormLabel').text('Edit '+$('#modalFormLabel').text());
                form.attr('action','/activities/'+$(e.relatedTarget).data('actid'));
                $('input[name="name"]').val($(e.relatedTarget).data('name').trim());
                $('input[name="color"]').val($(e.relatedTarget).data('color').trim());
            }
        });

        modal_confirm.on('show.bs.modal', function(e){
            $('strong[name="confActName"]').text($(e.relatedTarget).data('name').trim());
            if($(e.relatedTarget).data('href')){
                $('a[name="btnYesConfirm"]').attr('href', $(e.relatedTarget).data('href'));
            }
        });
    });
</script>
{% endblock %}
{% block body %}
{% load modals %}
{% load pagination %}
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-10 mt-5">
                <div class="text-white">
                    <h5 class="lead">My activities</h5>
                    <div>
                        {% for act in page_obj %}
                            {% if forloop.first %}
                                <div class="table-responsive">
                                    <table class="table table-dark m-0" id='actList'>
                                        <thead>
                                            <tr>
                                                <th scope="col">#</th>
                                                <th scope="col">Name</th>
                                                <th scope="col"></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                            {% endif %}
                                <tr name='act{{ act.id }}'>
                                    <th scope="row">
                                        <p>
                                            {{ forloop.counter}}
                                        </p>
                                    </th>
                                    <td name='name'>
                                        <p>
                                            {{ act.name }}
                                            {% if act.get_open_appointments.first.has_open_break %}
                                                <span class="badge badge-pill badge-danger">Paused</span>
                                            {% elif act.get_open_appointments %}
                                                <span class="badge badge-pill badge-info">In progress</span>
                                            {% endif %}
                                        </p>
                                    </td>
                                    <td class='text-right'>
                                        <a href="{% url 'activity:activity_details' act.id %}" class="btn btn-primary mr-md-2">
                                            <i class="fa fa-eye"></i>
                                        </a>
                                        <button type='button' class="btn btn-warning mr-2 d-none d-md-inline" data-toggle="modal" data-target="#modalForm" data-actid='{{ act.id }}' data-color='{{ act.color }}' data-name="{{ act.name }}">
                                            <i class="fa fa-pencil"></i>
                                        </button>
                                        <button type="button" class="btn btn-danger d-none d-md-inline" data-toggle="modal" data-target="#modalConfirm" data-name="{{ act.name }}" data-href="{% url 'activity:delete_activity' act.id %}">
                                            <i class="fa fa-times"></i>
                                        </button>
                                    </td>
                                </tr>
                            {% if forloop.last %}
                                        </tbody>
                                    </table>
                                </div>
                            {% endif %}
                        {% empty %}
                            <div class="text-center">
                                <h5 class='p-2'>No activities found!</h5>
                            </div>
                        {% endfor %} 
                        {% create_pagination page_obj %}
                    </div>
                    <div class="text-right mt-2">
                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#modalForm">
                            <i class="fa fa-plus-circle"></i>
                            New activity
                        </button>
                    </div> 
                </div>
            </div>              
        </div>
        {% create_modal_form "Activity" form  "POST" "actForm" %}
        {% create_modal_confirm "Delete activity" "<p>Do you really wish to delete the activity <strong name='confActName'></strong></p>" False %}
    </div>
{% endblock %}

appointer/activity/templates/activity_details.html
{% extends "base.html" %}
{% block pagescript %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        var ctx = $("#progressChart");
        var raw = JSON.parse(ctx.data('appoints').replace(/'/g, "\"").replace(/False/g, "0").replace(/True/g, "1"));
        var chartData = [];
        var chartLabels = [];
        raw.weeks.forEach(week => {
            week.forEach(day =>{
                if(day.used === 1){
                    chartLabels.push(day.day);
                    chartData.push(parseInt(day.timespentint));
                }
            })
        });
        Chart.defaults.global.defaultFontColor = 'white';
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: chartLabels,
                datasets: [{
                    label: 'Appointed time/day (in seconds)',
                    data: chartData,
                    fill: false,
                    borderColor: raw.color
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
    });
</script>
{% endblock %}
{% load humanize %}
{% block body %}
    <div class="container pb-5">
        <!-- Act name + appoints view btn -->
        <div class="d-flex justify-content-between text-white mt-3">
            <h3 class="display-4">
                Activity: {{ activity.name }}
                {% if activity.get_open_appointments.first.has_open_break %}
                    <span class="badge badge-pill badge-info">Paused</span>
                {% endif %}
            </h3>
            {% if activity.appointments.count > 0 %}
            <a href="{% url 'activity:view_appoints' activity.id %}" class="btn btn-success d-flex align-items-center rounded-circle px-4 py-4 py-md-0">
                <i class="fas fa-list-ul fa-lg"></i>
            </a>
            {% endif %}
        </div>
        <!-- Appoints today -->
        <div class="text-white">
            <h3 class='lead'>{% now "F jS, Y" %}</h3>
            <p id='TotalAppoints'>Appointments: {{ activity.appointments_today.count }}</p>
            <p>
                Total appointed time: {{ activity.total_appointed_time }}
            </p>
            {% if not activity.get_open_appointments %}
                <a href="{% url 'activity:new_appoint' activity.id %}" class="btn btn-success" data-actid='{{ activity.id }}' id='newAppoint'>
                    <i class="far fa-clock"></i>
                    New appointment
                </a>
            {% endif %}
            {% if activity.get_open_appointments %}
                <div id="openAppoint">
                    <h3>Open appointment</h3>
                    <p>Started at: {{ activity.get_open_appointments.first.starttime|time:"H:i:s" }}</p>
                    <div class="d-flex justify-content-between">
                        <a href="{% url 'activity:take_break' activity.id %}" class="btn btn-warning" {% if activity.get_open_appointments.first.has_open_break %} style='display:none;' {% endif %} id='takeBreak'>
                            <i class="fa fa-stopwatch"></i>
                            Take break
                        </a>
                        <a href="{% url 'activity:resume_break' activity.id %}" class="btn btn-warning" {% if not activity.get_open_appointments.first.has_open_break %} style='display:none;' {% endif %} id='resumeBreak'>
                            <i class="fa fa-history"></i>
                            Resume break
                        </a>
                        <a href="{% url 'activity:close_appoint' activity.id %}" class="btn btn-warning" id='endAppoint'>
                            <i class="fa fa-check-circle"></i>
                            End appointment
                        </a>
                    </div>
                </div>
            {% endif %}
        </div>
        <!-- Monthly overview -->
        <div class="mt-3 text-white text-center">
            <h3 class="display-4">Monthly overview</h3>
        </div>
        <div class="d-flex flex-column flex-lg-row justify-content-between mt-3 text-white">
            <div>
                <h3 class="lead">Appointed days</h3>
                <div class='table-responsive'>
                    <table class='table m-0 table-bordered text-white'>
                        <thead class="thead-dark border border-white">
                            <tr>
                                <th>Mon</th>
                                <th>Tue</th>
                                <th>Wed</th>
                                <th>Thu</th>
                                <th>Fri</th>
                                <th>Sat</th>
                                <th>Sun</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for week in monthlyApp.weeks %}
                                <tr>
                                    {% for day in week %}
                                        <td class="{% if day.totalappointments > 0 %} bg-success {% endif %} p-0">
                                            <span>    
                                                <div class='h-50 d-flex justify-content-between p-2'>
                                                {% if day.day != 0 %}
                                                    <small class="p-0">{{ day.day }}</small>
                                                    {% if day.totalappointments > 0 %}
                                                        <i class="fa fa-check"></i>
                                                    {% endif %}
                                                {% endif %}
                                                </div>
                                            </span>
                                        </td>
                                    {% endfor %}    
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card bg-transparent border-0">
                <div class="card-body p-0">
                    <h3 class="lead">Progression chart</h3>
                    <canvas class="h-100" id="progressChart" data-appoints="{{ monthlyApp }}"></canvas>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
    

appointer/activity/templates/appoints_list.html
{% extends "base.html" %}
{% block pagescript %}
<script type="text/javascript">
    $(document).ready(function(){
        var form = $('#appForm');
        var modal = $('#modalForm');

        modal.on('hidden.bs.modal', function(e){
            form.trigger('reset');
        });

        modal.on('show.bs.modal', function(e){
            form.attr("action", $(e.relatedTarget).data('url').trim());
            $('input[name="starttime"]').val($(e.relatedTarget).data('starttime').trim());
            $('input[name="timeend"]').val($(e.relatedTarget).data('timeend').trim());
        });
    });
</script>
{% endblock %}
{% load pagination %}
{% load modals %}
{% block body %}
    <div class="container mt-3">
        <h3 class="display-4 text-white">Appoints for {{ act.name }} - {% now "F" %}</h3>
        {% for app in page_obj %}
            {% if forloop.first %}
                <div>
                    <div class="table-responsive">
                        <table class="table table-dark m-0">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Start date</th>
                                    <th scope="col">End date</th>
                                    <th scope="col">Breaks taken</th>
                                    <th scope="col">Total time</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
            {% endif %}
                <tr>
                    <th scope="row">
                        <p>
                            {{ forloop.counter}}
                        </p>
                    </th>
                    <td>{{ app.starttime|date:"d/m/Y H:i:s" }}</td>
                    <td>{{ app.timeend|date:"d/m/Y H:i:s"|default:"Open" }}</td>
                    <td>{{ app.breaks.count }}</td>
                    <td>{{ app.totaltime }}</td>
                    <td class='text-right'>
                        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#modalForm" data-starttime='{{ app.starttime|date:"Y-m-d H:i:s" }}' data-timeend='{{ app.timeend|date:"Y-m-d H:i:s" }}' data-url='{% url "activity:edit_appoint" act.id app.id %}'>
                            <i class="fa fa-pencil"></i>
                        </button>
                    </td>
                </tr>
            {% if forloop.last %}
                        </tbody>
                    </table>
                </div>
            {% endif %}
        {% empty %}
        {% endfor %}
        {% create_pagination page_obj %}
        </div>
        {% create_modal_form "Edit appointment" form  "POST" "appForm" %}
    </div>
{% endblock %}
    